version: "3.8"

services:
  backend:
    build:
      context: ./superheroes-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BACKEND_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/superheroes
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      WEBSOCKET_TOPIC: /topic/battle-results
    depends_on:
      - db

  frontend:
    build:
      context: ./superheroes-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
      REACT_APP_WEBSOCKET_URL: http://localhost:8080/websocket

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: superheroes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
